# .github/workflows/deploy.yml
name: Deploy to AWS ECS via Pulumi

on:
  push:
    branches:
      - main # Or your primary deployment branch

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Required to check out the code

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # Optional: Link to a GitHub environment for secrets/protection rules
    # environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Pulumi CLI
        uses: pulumi/actions@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match version used for Pulumi project if needed

      - name: Install Pulumi Project Dependencies
        run: npm install --frozen-lockfile
        working-directory: ./pulumi # Run in the pulumi directory

      # --- Configure AWS Credentials using OIDC ---
      # Removed steps to get role ARN from Pulumi outputs
      # Using manually created role ARN directly
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::019997775122:role/admin-full-access-to-all # Hardcoded ARN
          aws-region: ${{ secrets.AWS_REGION }}

      # --- Login to ECR ---
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- Build and Push Docker Image ---
      - name: Define Image Tag
        id: image_tag
        # Use commit SHA for unique tags
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get ECR Repository Name from Pulumi Output
        id: get_ecr_repo
        run: |
          REPO_NAME=$(jq -r '.ecrRepositoryName' pulumi-outputs.json)
          echo "ECR_REPOSITORY=${REPO_NAME}" >> $GITHUB_ENV
          echo "Repository name: ${REPO_NAME}" # For logging

      - name: Download build-time env file from S3
        run: aws s3 cp s3://lawlzer-website-env/.env .env.build

      - name: Build, Tag, and Push Docker Image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.image_tag.outputs.tag }}
          DOCKER_BUILDKIT: 1 # Enable BuildKit for secrets
        run: |
          echo "Building image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          # Use BuildKit secrets to mount the .env file securely
          docker build --secret id=env,src=.env.build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          echo "Pushing image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        # working-directory: ./ # Build context is root

      # --- Deploy using Pulumi ---
      - name: Set Pulumi Image Config
        run: pulumi config set image ${{ steps.build-image.outputs.image }} --cwd ./pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          # AWS creds already configured via OIDC role

      - name: Update Pulumi Stack
        id: pulumi_up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: prod # Your stack name
          work-dir: ./pulumi # Run in the pulumi directory
          refresh: true # Refresh state before update
          suppress-progress: true # Reduce log verbosity during waits
          # config-map removed - now set explicitly in previous step
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          # AWS creds already configured via OIDC role

      - name: Show App URL after deploy
        run: |
          APP_URL=$(jq -r '.appUrl' pulumi-outputs.json) # Get URL from last output
          echo "Application successfully deployed."
          echo "Access URL: ${APP_URL}"
